name: Build
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Compile document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            tex/s3_en.tex
            tex/s3_de.tex
            tex/s3_en_de.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          extra_system_packages: "lilypond inkscape jinja2-cli tidyhtml zip"
          post_compile: |
            tex4ebook tex/s3_en.tex
            tex4ebook tex/s3_de.tex
            tex4ebook tex/s3_en_de.tex
            ls -la tex
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            *.pdf
            *.epub
          retention-days: 8
          overwrite: true

# vim: set et ai sw=2 ts=2 sts=2:

